// <auto-generated />
using ExamesClinpop_Lista.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamesClinpop_Lista.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230914153548_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamesClinpop_Lista.Data.Exame", b =>
                {
                    b.Property<int>("ExameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExameId"));

                    b.Property<string>("DescricaoExame")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeExame")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoExame")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ExameId");

                    b.ToTable("Exames");

                    b.HasData(
                        new
                        {
                            ExameId = 1,
                            DescricaoExame = "Exame de Sangue",
                            NomeExame = "V.D.R.L",
                            PrecoExame = 6m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
